
spring:
  application:
    name: LimitsInit
  sql:
      init:
          mode: always
  datasource:
        url: jdbc:postgresql://localhost:5436/gele_main?currentSchema=limits
        username: gele_usr
        password: gele_usr

