
spring:


  sql:
    init:
      mode: always
      data-locations: data-*.sql
  datasource:
    url: jdbc:postgresql://localhost:5436/gele_main?currentSchema=limits
    username: gele_usr
    password: gele_usr



logging:
  level:
    sql: debug

